#!/usr/bin/bash -x

LOC=/reg/d/ana01/temp/davidsch/lc2/runA
if [ ! -d $LOC ]
then
    echo "directory $LOC doesn't exist, set it to a output path for the hdf5 files, on a filesystem that supports SWMR";
    exit 1
fi

rm $LOC/vds_swmr*

h5c++ -Wall writer.cpp -o writer
h5c++ -Wall master.cpp -o master
h5c++ -Wall reader.cpp -o reader

./writer 0  $LOC/vds_swmr_writer_0.h5 &
./writer 1  $LOC/vds_swmr_writer_1.h5 &
./writer 2  $LOC/vds_swmr_writer_2.h5 &
./master $LOC/vds_swmr_master.h5 $LOC/vds_swmr_writer_0.h5 $LOC/vds_swmr_writer_1.h5 $LOC/vds_swmr_writer_2.h5
./reader 0  $LOC/vds_swmr_master.h5 &
./reader 1  $LOC/vds_swmr_master.h5 &

